#ifndef SELECTIONUSAGE_H
#define SELECTIONUSAGE_H

enum class SelectionUsage {
  DEFAULT = 0,
  ITSELF_ONLY = DEFAULT,
  INCLUDING_ITSELF_AND_ITS_RELATED,
  RELATED_JSON_ONLY,
  RELATED_VIDEO_ONLY,
};

#endif // SELECTIONUSAGE_H
