#include "ThumbnailActions.h"
#include "PublicMacro.h"
#include "NotificatorMacro.h"
#include "MenuToolButton.h"
#include "ImageTool.h"
#include "BehaviorKey.h"
#include "Configuration.h"
#include "GrabFramesDialog.h"
#include <QInputDialog>

ThumbnailActions& ThumbnailActions::GetInst() {
  static ThumbnailActions ins;
  return ins;
}

void setVideoStoryBoardDimension(QAction* pAct, int rowCnt, int colCnt, int widthPixel) {
  pAct->setProperty("rowCnt", rowCnt);
  pAct->setProperty("colCnt", colCnt);
  pAct->setProperty("widthPixel", widthPixel);
}

void setThumbnailExtractIndexRange(QAction* pAct, int startIndex, int endIndex) {
  pAct->setProperty("startIndex", startIndex);
  pAct->setProperty("endIndex", endIndex);
}

ThumbnailActions::ThumbnailActions(QObject* /*parent*/) {
  CREATE_THUMBNAIL_FOR_A_PATH = new (std::nothrow) QAction(QIcon{":img/THUMBNAIL"}, tr("Create thumbnail"), this);
  CREATE_THUMBNAIL_FOR_A_PATH->setToolTip("Create thumbnails for all folder(s) in current view");

  _SKIP_IF_ALREADY_EXIST = new (std::nothrow) QAction(QIcon{":img/SKIP_IF_EXIST"}, tr("Skip if already exist"), this);
  _SKIP_IF_ALREADY_EXIST->setCheckable(true);
  _SKIP_IF_ALREADY_EXIST->setChecked(true);

  GRAB_A_FRAME = new QAction{QIcon{":/VideoPlayer/GRAB_FRAME"}, tr("Grab a Frame"), this};
  GRAB_FRAMES_ADVANCE = new QAction{QIcon{":/VideoPlayer/GRAB_FRAMES"}, tr("Grab Frames"), this};

  _CREATE_THUMBNAIL_AG = new (std::nothrow) QActionGroup{this};
  {
    _CREATE_1_X_1_STORYBOARD = new (std::nothrow) QAction(QIcon(":img/THUMBNAILS_1_BY_1"), tr("Create 1x1 StoryBoard"), this);
    _CREATE_1_X_1_STORYBOARD->setToolTip("Create an 1x1 story board for video(s), each image width:720px");
    setVideoStoryBoardDimension(_CREATE_1_X_1_STORYBOARD, 1, 1, 720);
    _CREATE_THUMBNAIL_AG->addAction(_CREATE_1_X_1_STORYBOARD);
  }
  {
    _CREATE_2_X_2_STORYBOARD = new (std::nothrow) QAction(QIcon(":img/THUMBNAILS_2_BY_2"), tr("Create 2x2 StoryBoard"), this);
    _CREATE_2_X_2_STORYBOARD->setToolTip("Create a 2x2 story board for video(s), each image width:720px");
    setVideoStoryBoardDimension(_CREATE_2_X_2_STORYBOARD, 2, 2, 720);
    _CREATE_THUMBNAIL_AG->addAction(_CREATE_2_X_2_STORYBOARD);
  }
  {
    _CREATE_3_X_3_STORYBOARD = new (std::nothrow) QAction(QIcon(":img/THUMBNAILS_3_BY_3"), tr("Create 3x3 StoryBoard"), this);
    _CREATE_3_X_3_STORYBOARD->setToolTip("Create a 3x3 story board for video(s), each image width:720px");
    setVideoStoryBoardDimension(_CREATE_3_X_3_STORYBOARD, 3, 3, 720);
    _CREATE_THUMBNAIL_AG->addAction(_CREATE_3_X_3_STORYBOARD);
  }
  {
    _CREATE_4_X_4_STORYBOARD = new (std::nothrow) QAction(QIcon(":img/THUMBNAILS_4_BY_4"), tr("Create 4x4 StoryBoard"), this);
    _CREATE_4_X_4_STORYBOARD->setToolTip("Create a 4x4 story board for video(s), each image width:480px");
    setVideoStoryBoardDimension(_CREATE_4_X_4_STORYBOARD, 4, 4, 480);
    _CREATE_THUMBNAIL_AG->addAction(_CREATE_4_X_4_STORYBOARD);
  }

  _RENAME_STORYBOARD_FROM_POT_PLAYER = new (std::nothrow) QAction(QIcon{":img/RENAME_STORYBOARD"}, tr("Update storyboard name"), this);
  _RENAME_STORYBOARD_FROM_POT_PLAYER->setToolTip("Update storyboard thumbnail images name generated by potplayer");

  _EXTRACT_THUMBNAIL_AG = new (std::nothrow) QActionGroup{this};
  {
    _EXTRACT_1ST_IMG = new (std::nothrow) QAction(QIcon(":img/THUMBNAIL_EXTRACTOR_0_1"), tr("Extract [0, 1) imgs"), this);
    _EXTRACT_1ST_IMG->setToolTip("Extract the 1st image from story board under current view path");
    setThumbnailExtractIndexRange(_EXTRACT_1ST_IMG, 0, 1);
    _EXTRACT_THUMBNAIL_AG->addAction(_EXTRACT_1ST_IMG);
  }
  {
    _EXTRACT_2ND_IMGS = new (std::nothrow) QAction(QIcon(":img/THUMBNAIL_EXTRACTOR_0_2"), tr("Extract [0, 2) imgs"), this);
    _EXTRACT_2ND_IMGS->setToolTip("Extract the [0, 2) images from story board under current view path");
    setThumbnailExtractIndexRange(_EXTRACT_2ND_IMGS, 0, 2);
    _EXTRACT_THUMBNAIL_AG->addAction(_EXTRACT_2ND_IMGS);
  }
  {
    _EXTRACT_4TH_IMGS = new (std::nothrow) QAction(QIcon(":img/THUMBNAIL_EXTRACTOR_0_4"), tr("Extract [0, 4) imgs"), this);
    _EXTRACT_4TH_IMGS->setToolTip("Extract the [0, 4) images from story board under current view path");
    setThumbnailExtractIndexRange(_EXTRACT_4TH_IMGS, 0, 4);
    _EXTRACT_THUMBNAIL_AG->addAction(_EXTRACT_4TH_IMGS);
  }

  _CUSTOM_RANGE_IMGS = new (std::nothrow) QAction(QIcon(":img/THUMBNAIL_EXTRACTOR_B_E"), tr("Extract [b, e) imgs"), this);
  _CUSTOM_RANGE_IMGS->setToolTip("Extract the [b, e) images from story board under current view path");

  subscribe();
}

void ThumbnailActions::subscribe() {
  connect(_CREATE_THUMBNAIL_AG, &QActionGroup::triggered, this, [this](QAction* pAct) {
    CHECK_NULLPTR_RETURN_VOID(pAct);
    const int dimensionX = pAct->property("rowCnt").toInt();
    const int dimensionY = pAct->property("colCnt").toInt();
    const int widthPixel = pAct->property("widthPixel").toInt();
    emit crtVideoStoryBoard(dimensionX, dimensionY, widthPixel, isSkipIfAlreadyExist());
  });

  connect(_EXTRACT_THUMBNAIL_AG, &QActionGroup::triggered, this, [this](QAction* pAct) {
    CHECK_NULLPTR_RETURN_VOID(pAct);
    const int startIndex = pAct->property("startIndex").toInt();
    const int endIndex = pAct->property("endIndex").toInt();
    emit extractImages(startIndex, endIndex, isSkipIfAlreadyExist());
  });

  connect(_CUSTOM_RANGE_IMGS, &QAction::triggered, this, &ThumbnailActions::emitCustomFramesRange);

  connect(GRAB_A_FRAME, &QAction::triggered, this, [this]() {
    emit grabFrames(ImageTool::DEFAULT_START_POSITION_SECOND, ImageTool::DEFAULT_INTERVAL_SECOND, ImageTool::DEFAULT_FRAMES_COUNT, isSkipIfAlreadyExist());
  });

  connect(GRAB_FRAMES_ADVANCE, &QAction::triggered, this, [this]() {
    GrabFramesDialog dlg;
    if (dlg.exec() != QDialog::DialogCode::Accepted) {
      LOG_INFO_NP("Skip grab", "user cancelled");
      return;
    }
    emit grabFrames(dlg.startPositionSecond(), dlg.intervalSecond(), dlg.framesCount(), isSkipIfAlreadyExist());
  });
}

void ThumbnailActions::emitCustomFramesRange() {
  bool ok = false;
  const QString input = QInputDialog::getText(nullptr,                              //
                                              "Extract image range",                //
                                              "Enter range (e.g., 1,3; 1,4; 1,7):", //
                                              QLineEdit::Normal,
                                              "0,9",
                                              &ok); //
  if (!ok || input.isEmpty()) {
    LOG_INFO_P("[Skip] User canceled or invalid input", "input[%s]", qPrintable(input));
    return;
  }
  const int dotIndex = input.indexOf(',');
  if (dotIndex == -1 || input.count(',') != 1) {
    LOG_WARN_NP("Invalid Range Format", input);
    return;
  }
  const int startIndex = input.leftRef(dotIndex).toInt();
  const int endIndex = input.midRef(dotIndex + 1).toInt();
  if (startIndex < 0 || endIndex < startIndex) {
    LOG_WARN_P("Invalid range", "Ensure 0 < beg <= end but[%s]", qPrintable(input));
    return;
  }
  emit extractImages(startIndex, endIndex, isSkipIfAlreadyExist());
}

QWidget* ThumbnailActions::GetThumbnailFrameTools(QWidget* parent) {
  CHECK_NULLPTR_RETURN_NULLPTR(parent);
  QToolBar* frameTB = new (std::nothrow) QToolBar{"Thumbnail/Frame Tools", parent};
  CHECK_NULLPTR_RETURN_NULLPTR(frameTB);
  frameTB->setOrientation(Qt::Orientation::Vertical);
  frameTB->setToolButtonStyle(Qt::ToolButtonStyle::ToolButtonTextBesideIcon);
  frameTB->addAction(CREATE_THUMBNAIL_FOR_A_PATH);
  frameTB->addAction(GRAB_A_FRAME);
  frameTB->addAction(GRAB_FRAMES_ADVANCE);
  frameTB->setIconSize(QSize{IMAGE_SIZE::TABS_ICON_IN_MENU_16, IMAGE_SIZE::TABS_ICON_IN_MENU_16});
  return frameTB;
}

QWidget* ThumbnailActions::GetStoryBoardToolbar(QWidget* parent) {
  CHECK_NULLPTR_RETURN_NULLPTR(parent);

  QToolBar* storyBoardTB = new (std::nothrow) QToolBar{"StoryBoard Tools", parent};
  CHECK_NULLPTR_RETURN_NULLPTR(storyBoardTB);
  storyBoardTB->setOrientation(Qt::Orientation::Vertical);
  storyBoardTB->setToolButtonStyle(Qt::ToolButtonStyle::ToolButtonTextBesideIcon);
  storyBoardTB->addAction(_RENAME_STORYBOARD_FROM_POT_PLAYER);
  {
    auto* crtVidStoryBoard = new (std::nothrow) MenuToolButton{_CREATE_THUMBNAIL_AG->actions(),               //
                                                               QToolButton::MenuButtonPopup,                  //
                                                               Qt::ToolButtonStyle::ToolButtonTextBesideIcon, //
                                                               IMAGE_SIZE::TABS_ICON_IN_MENU_16,              //
                                                               storyBoardTB};                                 //
    CHECK_NULLPTR_RETURN_NULLPTR(crtVidStoryBoard);
    crtVidStoryBoard->InitDefaultActionFromQSetting(BehaviorKey::THUMBNAILS_DIMENSION, true);
    storyBoardTB->addWidget(crtVidStoryBoard);
  }

  {
    QList<QAction*> extractThumbnailActions;
    extractThumbnailActions += _EXTRACT_THUMBNAIL_AG->actions();
    extractThumbnailActions.push_back(nullptr);
    extractThumbnailActions.push_back(_CUSTOM_RANGE_IMGS);
    auto* extractTB = new (std::nothrow) MenuToolButton{extractThumbnailActions,                       //
                                                        QToolButton::MenuButtonPopup,                  //
                                                        Qt::ToolButtonStyle::ToolButtonTextBesideIcon, //
                                                        IMAGE_SIZE::TABS_ICON_IN_MENU_16,              //
                                                        storyBoardTB};                                 //
    CHECK_NULLPTR_RETURN_NULLPTR(extractTB);
    extractTB->InitDefaultActionFromQSetting(BehaviorKey::EXTRACT_CHOICE, true);
    storyBoardTB->addWidget(extractTB);
  }
  return storyBoardTB;
}
